name: Publish Porxy Package

on:
  push:
    branches: [feat/api-provider-proxy]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get cache date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: '6.23.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: cd packages/provider-proxy & pnpm install
      - run: pnpm build
